version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Decode GCP Service Account Key
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json

      - run:
          name: Authenticate with GCP
          command: |
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials $GKE_CLUSTER_NAME

      - run:
          name: Configure Docker with Artifact Registry
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev

      - run:
          name: Build Docker image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest .

      - run:
          name: Push Docker image
          command: |
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest

      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f deployment.yaml

workflows:
  deploy-workflow:
    jobs:
      - build-and-deploy
